apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadndco7179-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadndco7179-tenant-component
    app.kubernetes.io/part-of: loadndco7179-tenant-app
  name: loadndco7179-tenant-component
  namespace: loadndco7179-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadndco7179-tenant-component
status:
  loadBalancer: {}
